# Usa l'immagine ufficiale di Nginx
FROM nginx:latest

# Copia la configurazione di Nginx nel container
COPY ./config/nginx.conf /etc/nginx/nginx.conf

# Copia il tuo sito nella directory di lavoro di Nginx
COPY ./public /var/www/html
