version: '3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
